spring:
  profiles:
    include: core

server:
  port: 8080

logging:
  level:
    com.bizreport.api: debug

api:
  nts:
    url: "https://api.odcloud.kr/api/nts-businessman/v1/status"
    key: ${NTS_API_KEY}

dir:
  upload:
    card: "src/test/resources/temp/card/"
  download:
    card: "src/main/resources/static/"