spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

batch:
  chunk:
    business: 500
    data: 500
    report: 100
    api: 100

api:
  nts:
    url: "https://api.odcloud.kr/api/nts-businessman/v1/status"
    key: ${NTS_API_KEY}

shedlock:
  table-name: shedlock